-- KaçaGider Satıcı + Telefoncu Güven Sistemi
-- Bu dosya Supabase SQL Editor'da manuel uygulanmak üzere hazırlanmıştır.
-- Amaç: kullanıcıya dönük güven puanını, doğrulama rozetlerini ve işlem geçmişi sinyallerini
-- ilan fiyatı / KaçaGider piyasa değerinden tamamen bağımsız tutmak.

create table if not exists public.trust_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  account_type text not null default 'seller' check (account_type in ('seller','dealer')),
  display_name text,
  phone_verified boolean not null default false,
  identity_verified boolean not null default false,
  dealer_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trust_events (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  points smallint not null check (points between -50 and 50),
  reference_id text,
  note text,
  created_at timestamptz not null default now()
);

create unique index if not exists trust_events_unique_reference_idx
  on public.trust_events(actor_id,event_type,reference_id)
  where reference_id is not null;

create index if not exists trust_events_actor_idx
  on public.trust_events(actor_id,created_at desc);

alter table public.trust_profiles enable row level security;
alter table public.trust_events enable row level security;

-- Kullanıcı yalnızca kendi profil satırını okuyabilir. Dışarıya açık veri RPC ile döner.
drop policy if exists trust_profiles_select_own on public.trust_profiles;
create policy trust_profiles_select_own
  on public.trust_profiles for select
  to authenticated
  using (auth.uid() = user_id);

-- Kullanıcı trust_events tablosuna doğrudan yazamaz/okuyamaz.
-- Olaylar yalnızca güvenilir backend / servis rolü / yönetim akışı tarafından oluşturulmalıdır.

create or replace function public.upsert_my_trust_profile(
  p_display_name text default null,
  p_account_type text default 'seller'
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;

  if p_account_type not in ('seller','dealer') then
    raise exception 'invalid_account_type';
  end if;

  insert into public.trust_profiles(user_id,account_type,display_name,updated_at)
  values (
    auth.uid(),
    p_account_type,
    nullif(left(trim(coalesce(p_display_name,'')),120),''),
    now()
  )
  on conflict (user_id) do update set
    account_type = excluded.account_type,
    display_name = coalesce(excluded.display_name,public.trust_profiles.display_name),
    updated_at = now();
end;
$$;

revoke all on function public.upsert_my_trust_profile(text,text) from public;
grant execute on function public.upsert_my_trust_profile(text,text) to authenticated;

create or replace function public.get_public_trust_profile(p_user_id uuid)
returns table (
  user_id uuid,
  account_type text,
  display_name text,
  trust_score integer,
  trust_label text,
  email_verified boolean,
  phone_verified boolean,
  identity_verified boolean,
  dealer_verified boolean,
  published_listing_count integer,
  completed_transaction_count integer,
  positive_signal_count integer,
  negative_signal_count integer,
  account_age_days integer
)
language sql
stable
security definer
set search_path = public, auth
as $$
with base as (
  select
    u.id as uid,
    coalesce(tp.account_type,'seller') as account_type,
    coalesce(nullif(tp.display_name,''),nullif(u.raw_user_meta_data->>'full_name',''),'KaçaGider kullanıcısı') as display_name,
    (u.email_confirmed_at is not null) as email_verified,
    coalesce(tp.phone_verified,false) as phone_verified,
    coalesce(tp.identity_verified,false) as identity_verified,
    coalesce(tp.dealer_verified,false) as dealer_verified,
    greatest(0,floor(extract(epoch from (now()-u.created_at))/86400)::int) as account_age_days,
    (
      select count(*)::int from public.listings l
      where l.user_id=u.id and l.status='published'
    ) as published_listing_count,
    (
      select count(*)::int from public.trust_events e
      where e.actor_id=u.id and e.event_type in ('sale_completed','purchase_completed','dealer_offer_completed')
    ) as completed_transaction_count,
    (
      select count(*)::int from public.trust_events e
      where e.actor_id=u.id and e.points > 0
    ) as positive_signal_count,
    (
      select count(*)::int from public.trust_events e
      where e.actor_id=u.id and e.points < 0
    ) as negative_signal_count,
    coalesce((select sum(e.points)::int from public.trust_events e where e.actor_id=u.id),0) as event_points
  from auth.users u
  left join public.trust_profiles tp on tp.user_id=u.id
  where u.id=p_user_id
), scored as (
  select *,
    greatest(0,least(100,
      45
      + case when email_verified then 10 else 0 end
      + case when phone_verified then 8 else 0 end
      + case when identity_verified then 12 else 0 end
      + case when account_type='dealer' and dealer_verified then 15 else 0 end
      + least(10,published_listing_count*2)
      + least(8,completed_transaction_count*2)
      + case when account_age_days >= 180 then 7 when account_age_days >= 30 then 4 else 0 end
      + greatest(-30,least(25,event_points))
    ))::int as trust_score
  from base
)
select
  uid,
  account_type,
  display_name,
  trust_score,
  case
    when trust_score >= 90 then 'Çok Güvenilir'
    when trust_score >= 80 then 'Güvenilir'
    when trust_score >= 70 then 'İyi'
    when trust_score >= 55 then 'Gelişiyor'
    else 'Yeni Hesap'
  end as trust_label,
  email_verified,
  phone_verified,
  identity_verified,
  dealer_verified,
  published_listing_count,
  completed_transaction_count,
  positive_signal_count,
  negative_signal_count,
  account_age_days
from scored;
$$;

revoke all on function public.get_public_trust_profile(uuid) from public;
grant execute on function public.get_public_trust_profile(uuid) to anon, authenticated;

-- Yönetim/backend tarafında örnek güven olayları:
-- sale_completed          +8
-- dealer_offer_completed  +6
-- positive_feedback       +4
-- no_show / fake_listing -15
-- cancelled_after_agree  -8
-- Bu olayları istemci tarafında doğrudan insert etmeyin.
