create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin', 'super_admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;
grant select on table public.admin_users to authenticated;

do $storage$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'admin_users'
      and policyname = 'admin_users_self_select'
  ) then
    execute 'create policy admin_users_self_select on public.admin_users for select to authenticated using ((select auth.uid()) = user_id)';
  end if;
end $storage$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and active = true
      and role in ('admin', 'super_admin')
  );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='listings' and policyname='listings_admin_select') then
    execute 'create policy listings_admin_select on public.listings for select to authenticated using ((select public.is_admin()))';
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='listing_photos' and policyname='listing_photos_admin_select') then
    execute 'create policy listing_photos_admin_select on public.listing_photos for select to authenticated using ((select public.is_admin()))';
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles_admin_select') then
    execute 'create policy profiles_admin_select on public.profiles for select to authenticated using ((select public.is_admin()))';
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'listing_images_admin_delete'
  ) then
    execute $sql$create policy listing_images_admin_delete on storage.objects
      for delete to authenticated
      using (bucket_id = 'listing-images' and (select public.is_admin()))$sql$;
  end if;
end $$;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

alter table public.admin_audit_log enable row level security;
revoke all on table public.admin_audit_log from anon, authenticated;
grant select on table public.admin_audit_log to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'admin_audit_log'
      and policyname = 'admin_audit_log_admin_select'
  ) then
    execute 'create policy admin_audit_log_admin_select on public.admin_audit_log for select to authenticated using ((select public.is_admin()))';
  end if;
end $$;

create or replace function public.admin_list_users()
returns table (
  id uuid,
  email text,
  full_name text,
  phone text,
  city text,
  district text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Yönetici yetkisi gerekli.' using errcode = '42501';
  end if;

  return query
  select u.id, u.email, p.full_name, p.phone, p.city, p.district,
         u.created_at, u.last_sign_in_at, (u.email_confirmed_at is not null)
  from auth.users u
  left join public.profiles p on p.id = u.id
  order by u.created_at desc;
end;
$$;

create or replace function public.admin_list_audit_logs()
returns table (
  id bigint,
  admin_user_id uuid,
  action text,
  target_type text,
  target_id uuid,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Yönetici yetkisi gerekli.' using errcode = '42501';
  end if;

  return query
  select l.id, l.admin_user_id, l.action, l.target_type, l.target_id,
         l.metadata, l.created_at
  from public.admin_audit_log l
  order by l.created_at desc
  limit 500;
end;
$$;

create or replace function public.admin_set_listing_status(
  p_listing_id uuid,
  p_status text
)
returns public.listings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old public.listings;
  v_new public.listings;
begin
  if not public.is_admin() then
    raise exception 'Yönetici yetkisi gerekli.' using errcode = '42501';
  end if;
  if p_status not in ('draft', 'published', 'sold', 'archived') then
    raise exception 'Geçersiz ilan durumu.' using errcode = '22023';
  end if;

  select * into v_old from public.listings where id = p_listing_id;
  if not found then
    raise exception 'İlan bulunamadı.' using errcode = 'P0002';
  end if;

  update public.listings
  set status = p_status,
      published_at = case when p_status = 'published' and published_at is null then now() else published_at end,
      updated_at = now()
  where id = p_listing_id
  returning * into v_new;

  insert into public.admin_audit_log (admin_user_id, action, target_type, target_id, metadata)
  values ((select auth.uid()), 'listing_status_changed', 'listing', p_listing_id,
          jsonb_build_object('old_status', v_old.status, 'new_status', v_new.status));

  return v_new;
end;
$$;

create or replace function public.admin_delete_listing(p_listing_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_listing public.listings;
begin
  if not public.is_admin() then
    raise exception 'Yönetici yetkisi gerekli.' using errcode = '42501';
  end if;

  select * into v_listing from public.listings where id = p_listing_id;
  if not found then
    raise exception 'İlan bulunamadı.' using errcode = 'P0002';
  end if;

  delete from public.listings where id = p_listing_id;

  insert into public.admin_audit_log (admin_user_id, action, target_type, target_id, metadata)
  values ((select auth.uid()), 'listing_deleted', 'listing', p_listing_id,
          jsonb_build_object('brand', v_listing.brand, 'model', v_listing.model,
                             'seller_price', v_listing.seller_price, 'status', v_listing.status));

  return true;
end;
$$;

revoke all on function public.admin_list_users() from public, anon;
revoke all on function public.admin_list_audit_logs() from public, anon;
revoke all on function public.admin_set_listing_status(uuid, text) from public, anon;
revoke all on function public.admin_delete_listing(uuid) from public, anon;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_list_audit_logs() to authenticated;
grant execute on function public.admin_set_listing_status(uuid, text) to authenticated;
grant execute on function public.admin_delete_listing(uuid) to authenticated;
